version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db

  staff-service:
    build: .
    container_name: staff_service
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=staff_service
      - JWT_SECRET=supersecret
    ports:
      - "8005:8005"

volumes:
  mongo_data: